import { useTranslation } from 'react-i18next'

const en = {
  free: 'Free to use. Your AI, your choice.',
  demoTitle: 'Less back-and-forth. More done.',
  demoBody: 'Give a task to your team. Watch them research, build, and bring the pieces together.',
  demo: 'Interactive demo',
  demoNote: 'A scripted preview. No files, providers, or tools are connected.',
  team: 'Your team',
  channel: 'Project launch',
  you: 'You',
  run: 'Run this demo',
  replay: 'Replay demo',
  done: 'Ready for your review',
  working: 'Team is working',
  scenarios: [
    {
      name: 'Plan a launch',
      prompt:
        'Turn my notes into a launch plan. Research the market, draft the page, and give me a checklist.',
      messages: [
        'I’ll split this into research, a first draft, and a launch checklist. Scout, start with the market.',
        'I found the positioning themes. Keeping the sources alongside the summary for review.',
        'I’ve drafted the page from your notes and Scout’s findings. The files are ready to review.',
        'The draft and research are together. Here’s the launch checklist—your turn to make the call.',
      ],
      file: 'launch-plan.md',
      result: ['Review the positioning', 'Approve the page draft', 'Choose a launch date'],
    },
    {
      name: 'Build a feature',
      prompt:
        'Review the project folder, build the next feature, and explain the changes before I ship.',
      messages: [
        'I’ll coordinate the work. Builder, read the project and propose the change first.',
        'The relevant files are identified. I’ll keep the change focused and run the project checks.',
        'The feature is drafted. I’m reviewing the diff against the original request.',
        'Here are the changes and check results. Review the diff before shipping.',
      ],
      file: 'feature-review.md',
      result: ['Read the change summary', 'Review the file diff', 'Confirm the checks'],
    },
    {
      name: 'Write a brief',
      prompt:
        'Read my project notes, pull out the important decisions, and turn them into a clear brief.',
      messages: [
        'I’ll organize the brief around the goal, the audience, and the decisions still open.',
        'I’ve pulled the key points from the notes, keeping assumptions separate from decisions.',
        'The first draft is ready. I’ve tightened the structure and highlighted the open questions.',
        'Your brief is ready to review. The original notes stay beside the draft.',
      ],
      file: 'project-brief.md',
      result: ['Check the project goal', 'Resolve open questions', 'Share the approved brief'],
    },
  ],
  featuresTitle: 'A little app. A lot of possibility.',
  featuresBody:
    'Real work happens in the details. Give each teammate a role, a folder, and the tools it needs.',
  cards: [
    {
      title: 'A team, in one conversation.',
      body: 'Named bots with their own instructions. Bring them into a group, mention a teammate, and hand work between them.',
    },
    {
      title: 'Your files. Real changes.',
      body: 'Read, edit, and create files. Run commands in the folder you assign, and see what happened.',
    },
    {
      title: 'Pick up where you left off.',
      body: 'Bots keep notes across chats. Give them useful context once and build on it next time.',
    },
    {
      title: 'Put repeat work on a routine.',
      body: 'Schedule a task for a bot on its computer. Your Runner needs to be online to do the work.',
    },
    {
      title: 'Tools that fit your work.',
      body: 'Connect apps through MCP plugins. Review permission requests before a tool gets access.',
    },
    {
      title: 'At your desk. In your pocket.',
      body: 'Keep chatting from a paired phone. Your computer runs the task; encrypted replies follow you.',
    },
  ],
  preview: 'Illustrative task details',
  read: 'Read project notes',
  handoff: 'Scout → Builder',
  review: 'Chef → You',
  files: 'Project folder',
  edited: 'Draft updated',
  remembered: 'Remembered for next time',
  memory: 'Use a clear, direct voice. Keep sources beside the research.',
  routine: 'Weekly project review',
  schedule: 'Mondays · 09:00',
  permission: 'Permission required',
  permissionBody: 'Connect the tools you choose.',
  devices: 'Computer → encrypted relay → phone',
  providersTitle: 'Your favorite AI. Together here.',
  providersBody:
    'Use an eligible subscription, connect an API key, or add a compatible model server. Choose a provider for each bot.',
  subscription: 'Subscription sign-in',
  api: 'API key',
  compatible: 'Compatible servers',
  compatibleBody: 'OpenAI or Anthropic-compatible endpoints, including your own model server.',
  providerDocs: 'See provider setup',
  pricingTitle: 'The app is free. The choice is yours.',
  priceBody:
    'Beans costs $0. You pay your AI provider directly through your subscription or API usage.',
  priceLabel: 'for Beans',
  included: [
    'Desktop apps and paired phones',
    'Named bots and group chats',
    'Files, memory, routines, and MCP tools',
  ],
  subscriptionTitle: 'Already have a plan?',
  subscriptionBody:
    'Connect ChatGPT or Grok with an eligible account. Your provider’s usage limits still apply.',
  apiTitle: 'Prefer an API key?',
  apiBody:
    'Connect Anthropic, DeepSeek, OpenCode, or a compatible endpoint. Usage is billed by that provider at its own rates.',
  costNote:
    'AI usage is separate from Beans. Running more bots can use more of your provider allowance. Your own computer also needs to stay online.',
  compareTitle: 'Find the right home for your AI.',
  compareBody: 'Compare how the work runs, how you connect models, and what you pay for.',
  compareAll: 'Explore comparisons',
  footerBody: 'AI teammates on your computer. Your models, your tools, your space.',
  product: 'Product',
  resources: 'Resources',
  providers: 'Providers',
  comparisons: 'Compare',
  source: 'Source code',
  releases: 'Releases',
  privacy: 'Privacy',
  support: 'Support',
  costs: 'Costs',
  features: 'Features',
  docs: 'Documentation',
  download: 'Download Beans',
  footerNote: 'Built for Mac, Windows, Linux, and paired phones.',
}
const zh: typeof en = {
  free: '免费使用，自由选择 AI。',
  demoTitle: '少一点往返，多一点完成。',
  demoBody: '把任务交给团队，看它们研究、构建并整理结果。',
  demo: '互动演示',
  demoNote: '预设演示，未连接文件、模型或工具。',
  team: '你的团队',
  channel: '项目发布',
  you: '你',
  run: '运行演示',
  replay: '重播演示',
  done: '等待你审核',
  working: '团队正在工作',
  scenarios: [
    {
      name: '准备发布',
      prompt: '把笔记整理成发布计划，研究市场、起草页面，并给我一份检查清单。',
      messages: [
        '我会分成研究、草稿和检查清单。Scout 先研究市场。',
        '我整理了定位主题，保留来源供审核。',
        '我根据笔记和研究起草了页面，文件等待审核。',
        '草稿与研究已整理好。这是发布清单，请你做决定。',
      ],
      file: 'launch-plan.md',
      result: ['检查产品定位', '审核页面草稿', '选择发布日期'],
    },
    {
      name: '构建功能',
      prompt: '查看项目文件夹，构建下一个功能，并在发布前解释改动。',
      messages: [
        '我来协调工作。Builder 先读项目并提出方案。',
        '相关文件已找到。我会控制改动范围并运行检查。',
        '功能草稿已完成，正在核对需求和差异。',
        '改动和检查结果已整理，请在发布前审核。',
      ],
      file: 'feature-review.md',
      result: ['阅读改动说明', '审核文件差异', '确认检查结果'],
    },
    {
      name: '撰写简报',
      prompt: '阅读项目笔记，提取关键决定并写成清晰的简报。',
      messages: [
        '我会按目标、受众和待定事项组织简报。',
        '关键点已提取，假设和决定单独列出。',
        '初稿完成，结构已整理，待定问题已标明。',
        '简报等待审核，原始笔记保留在旁边。',
      ],
      file: 'project-brief.md',
      result: ['检查项目目标', '解决待定问题', '分享审核后的简报'],
    },
  ],
  featuresTitle: '小小应用，大有可能。',
  featuresBody: '真正的工作在细节里。为每位队友分配角色、文件夹和工具。',
  cards: [
    {
      title: '一个对话，一整个团队。',
      body: '每个智能体都有名称和指令。在群聊中 @ 队友，互相交接任务。',
    },
    {
      title: '你的文件，真正的改动。',
      body: '读写文件，在指定文件夹中运行命令，查看执行结果。',
    },
    {
      title: '接着上次继续。',
      body: '智能体跨对话保存笔记，建立上下文并继续工作。',
    },
    {
      title: '重复工作交给例行任务。',
      body: '让智能体按计划执行任务，运行设备需要保持在线。',
    },
    {
      title: '适合你的工具。',
      body: '通过 MCP 插件连接应用，在授权之前审核权限请求。',
    },
    {
      title: '桌面与口袋之间。',
      body: '从配对手机继续聊天。电脑运行任务，加密回复跟随你。',
    },
  ],
  preview: '示例任务细节',
  read: '阅读项目笔记',
  handoff: 'Scout → Builder',
  review: 'Chef → 你',
  files: '项目文件夹',
  edited: '草稿已更新',
  remembered: '已保存笔记',
  memory: '语气清晰直接，研究结果附上来源。',
  routine: '每周项目回顾',
  schedule: '周一 · 09:00',
  permission: '需要授权',
  permissionBody: '连接你选择的工具。',
  devices: '电脑 → 加密中继 → 手机',
  providersTitle: '喜欢的 AI，在这里汇合。',
  providersBody: '使用符合条件的订阅、API 密钥或兼容模型服务器，为每个智能体选择提供商。',
  subscription: '订阅登录',
  api: 'API 密钥',
  compatible: '兼容服务器',
  compatibleBody: '支持 OpenAI 或 Anthropic 兼容接口，包括你自己的模型服务器。',
  providerDocs: '查看提供商设置',
  pricingTitle: '应用免费，选择由你。',
  priceBody: 'Beans 费用为 $0。订阅或 API 使用费用直接付给 AI 提供商。',
  priceLabel: 'Beans 费用',
  included: ['桌面应用与配对手机', '命名智能体和群聊', '文件、记忆、例行任务和 MCP 工具'],
  subscriptionTitle: '已有订阅？',
  subscriptionBody: '用符合条件的账号连接 ChatGPT 或 Grok，提供商用量限制依然适用。',
  apiTitle: '更喜欢 API？',
  apiBody: '连接 Anthropic、DeepSeek、OpenCode 或兼容接口，使用费用按提供商的费率计收。',
  costNote: 'AI 使用费用与 Beans 分开。更多智能体可能消耗更多用量，电脑需要保持在线。',
  compareTitle: '为你的 AI 找到合适的家。',
  compareBody: '比较工作在哪里运行、如何连接模型以及费用。',
  compareAll: '浏览比较',
  footerBody: '电脑上的 AI 队友。你的模型、工具和空间。',
  product: '产品',
  resources: '资源',
  providers: '提供商',
  comparisons: '比较',
  source: '源代码',
  releases: '版本发布',
  privacy: '隐私',
  support: '支持',
  costs: '费用',
  features: '功能',
  docs: '文档',
  download: '下载 Beans',
  footerNote: '适用于 Mac、Windows、Linux 和配对手机。',
}
export function useMarketingCopy() {
  const { i18n } = useTranslation()
  return i18n.language === 'zh' ? zh : en
}
